### ISSUE TITLE
Reduce our build matrix

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/pe-parse#168]
Our build matrix is unnecessarily wide, which slows down each CI run (since separate VMs have to be spawned for each instance):

```yaml
  pe-parse:
    strategy:
      matrix:
        platform: ["ubuntu-18.04", "macos-latest"]
        build-type: ["Debug", "Release"]
        build-shared: ["0", "1"]
        compiler:
        - { CC: "clang", CXX: "clang++" }
        - { CC: "gcc", CXX: "g++" }
        exclude:
        - platform: macos-latest
          compiler: { CC: "gcc", CXX: "g++" }
```

We can flatten this a bit by running debug/release and shared/static builds in the same release jobs, as separate steps.
